# Generated by Django 2.2.12 on 2020-07-19 09:21

import app_accounts.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(default=35.811777, null=True)),
                ('lng', models.FloatField(default=50.905918, null=True)),
                ('province', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('mailing_address', models.TextField(max_length=2000, null=True)),
                ('number', models.PositiveIntegerField(null=True)),
                ('unit', models.PositiveIntegerField(blank=True, null=True)),
                ('mailing_code', models.CharField(max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10), app_accounts.models.validate_mailing_code])),
                ('reciver', models.BooleanField(default=False)),
                ('reciver_first_name', models.CharField(max_length=100, null=True)),
                ('reciver_last_name', models.CharField(max_length=100, null=True)),
                ('reciver_cellphone', models.CharField(max_length=11, null=True, validators=[django.core.validators.MinLengthValidator(11), app_accounts.models.validate_cellphone])),
                ('reciver_national_code', models.CharField(max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10), app_accounts.models.validate_national_code])),
            ],
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered', models.BooleanField(default=False, null=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('favorites', 'favorites'), ('pardakht', 'pardakht'), ('pardakht-shod', 'pardakht-shod'), ('canceled', 'canceled')], max_length=30, null=True)),
                ('order_number', models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.MinLengthValidator(13), app_accounts.models.validate_order_number])),
                ('total_price', models.PositiveIntegerField(default=0, null=True)),
                ('total_discount', models.PositiveIntegerField(default=0, null=True)),
                ('total_discount_price', models.PositiveIntegerField(default=0, null=True)),
                ('order_registration_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, default=False, null=True)),
                ('position', models.CharField(blank=True, choices=[('1', 'اماده سازی سفارش'), ('2', 'خروج  از مرکز پردازش'), ('3', 'دریافت در مرکز توزیع'), ('4', 'تحویل به مامور ارسال'), ('5', 'تحویل مرسوله به مشتری')], max_length=1, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_accounts.Address')),
            ],
        ),
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(default=0)),
                ('price', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('discount', models.PositiveIntegerField(default=0, null=True)),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('basket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_accounts.Basket')),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('offer', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No'), ('S', 'so-so')], max_length=1, null=True)),
                ('write_date', models.DateField(null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('viewpoint', models.TextField(max_length=2000, null=True)),
                ('buyer', models.BooleanField(default=False, null=True)),
                ('publish', models.BooleanField(default=False, null=True)),
                ('star', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='3', max_length=1, null=True)),
                ('count_like', models.PositiveIntegerField(default=0, null=True)),
                ('count_dislike', models.PositiveIntegerField(default=0, null=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('time_range', models.CharField(blank=True, choices=[('A', '9-12'), ('B', '12-3'), ('C', '3-6'), ('D', '6-9')], max_length=10, null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(50)])),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_date', models.DateField(null=True)),
                ('text', models.TextField(max_length=3000, null=True)),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReturningBasket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'active'), ('canceled', 'canceled'), ('accepted', 'accepted'), ('received', 'received')], max_length=10, null=True)),
                ('registration_date', models.DateField(null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_accounts.Address')),
                ('basket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_accounts.Basket')),
            ],
        ),
        migrations.CreateModel(
            name='ReturningDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returning_date', models.DateField(blank=True, null=True)),
                ('time_range', models.CharField(blank=True, choices=[('A', '9-14'), ('B', '14-8')], max_length=1, null=True)),
                ('capacity', models.PositiveIntegerField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(50)])),
            ],
        ),
        migrations.CreateModel(
            name='ReturningItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0, null=True)),
                ('purchase_amount', models.PositiveIntegerField(default=0, null=True)),
                ('reason', models.CharField(choices=[('1', 'سفارش به صورت کامل ارسال نشده'), ('2', 'سایز کالا مناسب نیست'), ('3', 'کالای غیر اصل دریافت کرده ام'), ('4', 'کالای دیگری ارسال شده است'), ('5', 'از خرید خود منصرف شدم'), ('6', 'رنگ کالای ارسال شده مغایرت دارد'), ('7', 'کالا با اطلاعات درج شده در سایت مغایرت دارد'), ('8', 'کالا ایراد ظاهری یا شکستگی دارد'), ('9', 'کارت گارانتی ارسال نشده')], max_length=1, null=True)),
                ('descriptions', models.TextField(max_length=3000, null=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('canceled', 'canceled'), ('accepted', 'accepted'), ('received', 'received')], max_length=10, null=True)),
                ('basket_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_accounts.BasketItem')),
                ('returning_basket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_accounts.ReturningBasket')),
            ],
        ),
        migrations.AddField(
            model_name='returningbasket',
            name='returning_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_accounts.ReturningDate'),
        ),
        migrations.AddField(
            model_name='returningbasket',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=3000, null=True)),
                ('buyer', models.BooleanField(default=False, null=True)),
                ('count_like', models.PositiveIntegerField(default=0, null=True)),
                ('count_dislike', models.PositiveIntegerField(default=0, null=True)),
                ('posted_date', models.DateField(null=True)),
                ('question', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_accounts.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RefundAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('C', 'canceled'), ('R', 'returned')], max_length=1, null=True)),
                ('paid', models.BooleanField(default=False, null=True)),
                ('amount', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('basket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_accounts.Basket')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('bank_kard', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.MinLengthValidator(16)])),
                ('foreign_national', models.BooleanField(default=False)),
                ('newsletter_receive', models.BooleanField(blank=True, default=False, null=True)),
                ('national_code', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10), app_accounts.models.validate_national_code])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False, null=True)),
                ('dislike', models.BooleanField(default=False, null=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_accounts.Comment')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_accounts.Reply')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoodBadPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(choices=[('good', 'goodpoint'), ('bad', 'badpoint')], default='good', max_length=10, null=True)),
                ('item', models.CharField(max_length=200, null=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_accounts.Comment')),
            ],
        ),
        migrations.AddField(
            model_name='basket',
            name='deliverydate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_accounts.DeliveryDate'),
        ),
        migrations.AddField(
            model_name='basket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='address',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_accounts.Profile'),
        ),
    ]
