# Generated by Django 2.2.12 on 2020-07-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0002_auto_20200719_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='total_discount_price',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
