# Generated by Django 2.2.12 on 2020-04-27 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0003_basketitem_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
