# Generated by Django 2.2.12 on 2020-07-27 18:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_accounts', '0005_profile_validation_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='validation_code',
        ),
        migrations.CreateModel(
            name='ValidationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation_code', models.CharField(max_length=4, null=True, validators=[django.core.validators.MinLengthValidator(4)])),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
