# Generated by Django 2.2.12 on 2020-04-27 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0005_auto_20200427_0742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketitem',
            name='price',
        ),
    ]
