# Generated by Django 2.2.12 on 2020-04-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0006_remove_basketitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='on_off',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
