# Generated by Django 2.2.12 on 2020-08-03 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0007_auto_20200803_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='_birth_date',
        ),
    ]
