# Generated by Django 2.2.12 on 2020-05-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0007_auto_20200429_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('no active', 'no active')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
