# Generated by Django 2.2.12 on 2020-08-04 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0009_profile_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birth_date',
            new_name='_birth_date',
        ),
    ]
