# Generated by Django 2.2.12 on 2020-05-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0009_auto_20200501_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='on_off',
        ),
        migrations.AlterField(
            model_name='basket',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('no active', 'no active')], max_length=15, null=True),
        ),
    ]
