# Generated by Django 2.2.12 on 2020-08-24 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0012_auto_20200806_0827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bank_kard',
            new_name='bank_card',
        ),
    ]
