# Generated by Django 2.2.12 on 2020-09-14 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0013_auto_20200824_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='write_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
