# Generated by Django 2.2.12 on 2020-05-15 08:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0013_auto_20200512_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='mailing_code',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AddField(
            model_name='address',
            name='reciver',
            field=models.BooleanField(default=False),
        ),
    ]
