# Generated by Django 2.2.12 on 2020-05-16 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0014_auto_20200515_0804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
    ]
