# Generated by Django 2.2.12 on 2020-05-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0015_remove_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('no active', 'no active'), ('favarit', 'favarit')], max_length=15, null=True),
        ),
    ]
