# Generated by Django 2.2.12 on 2020-05-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0016_auto_20200516_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('no active', 'no active'), ('favorites', 'favorites')], max_length=15, null=True),
        ),
    ]
