# Generated by Django 2.2.12 on 2020-05-22 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0018_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bank_kard',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
