# Generated by Django 2.2.12 on 2020-05-22 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0019_profile_bank_kard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bank_kard',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.MinLengthValidator(16)]),
        ),
    ]
