# Generated by Django 2.2.12 on 2020-05-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0021_auto_20200522_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='foreign_national',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
