# Generated by Django 2.2.12 on 2020-05-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0022_profile_foreign_national'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foreign_national',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
