# Generated by Django 2.2.12 on 2020-05-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0023_auto_20200522_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foreign_national',
            field=models.BooleanField(default=False),
        ),
    ]
