# Generated by Django 2.2.12 on 2020-05-23 07:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0024_auto_20200522_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='national_code',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
