# Generated by Django 2.2.12 on 2020-05-25 11:36

import app_accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0026_auto_20200523_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10), app_accounts.models.validate_national_code]),
        ),
    ]
