# Generated by Django 2.2.12 on 2020-05-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0027_auto_20200525_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='pubish',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
