# Generated by Django 2.2.12 on 2020-05-29 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0029_auto_20200528_0907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='pubish',
            new_name='publish',
        ),
    ]
