# Generated by Django 2.2.12 on 2020-05-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0030_auto_20200529_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='write_date',
            field=models.DateTimeField(null=True),
        ),
    ]
