# Generated by Django 2.2.12 on 2020-05-31 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0035_comment_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='star',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='3', max_length=1, null=True),
        ),
    ]
