# Generated by Django 2.2.12 on 2020-06-02 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0037_auto_20200601_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='strengths',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='weak_points',
        ),
        migrations.CreateModel(
            name='GoodBadPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(blank=True, choices=[('good', 'goodpoint'), ('bad', 'badpoint')], max_length=10, null=True)),
                ('item', models.CharField(blank=True, max_length=200, null=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_accounts.Comment')),
            ],
        ),
    ]
