# Generated by Django 2.2.12 on 2020-06-04 11:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0040_auto_20200604_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='reciver_cellphone',
            field=models.CharField(max_length=11, null=True, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
    ]
