# Generated by Django 2.2.12 on 2020-06-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0043_auto_20200606_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='delivered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
