# Generated by Django 2.2.12 on 2020-06-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0044_basket_delivered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='order_registration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
