# Generated by Django 2.2.12 on 2020-06-06 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0046_auto_20200606_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_accounts.Address'),
        ),
    ]
