# Generated by Django 2.2.12 on 2020-06-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0048_auto_20200608_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='shipping_cost',
            field=models.FloatField(blank=True, default=10, null=True),
        ),
    ]
