# Generated by Django 2.2.12 on 2020-06-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0049_basket_shipping_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='delivered_date',
        ),
        migrations.AddField(
            model_name='basket',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
