# Generated by Django 2.2.12 on 2020-06-12 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0051_auto_20200612_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_accounts.Address'),
        ),
    ]
