# Generated by Django 2.2.12 on 2020-06-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0053_question_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='posted_date',
            field=models.DateField(null=True),
        ),
    ]
