# Generated by Django 2.2.12 on 2020-06-14 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0055_auto_20200613_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery_date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('time_range', models.CharField(blank=True, choices=[('A', '9-12'), ('B', '12-3'), ('C', '3-6'), ('D', '6-9')], max_length=10, null=True)),
                ('capacity', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='like',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_accounts.Response'),
        ),
        migrations.AddField(
            model_name='response',
            name='count_dislike',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='count_like',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
