# Generated by Django 2.2.12 on 2020-06-14 08:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_accounts', '0056_auto_20200614_0713'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='Reply',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='response',
            new_name='reply',
        ),
    ]
