# Generated by Django 2.2.12 on 2020-06-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0059_auto_20200614_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='posted_date',
            field=models.DateField(null=True),
        ),
    ]
