# Generated by Django 2.2.12 on 2020-06-15 11:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0060_reply_posted_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('time_range', models.CharField(blank=True, choices=[('A', '9-12'), ('B', '12-3'), ('C', '3-6'), ('D', '6-9')], max_length=10, null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(50)])),
            ],
        ),
        migrations.DeleteModel(
            name='Delivery_date',
        ),
        migrations.AddField(
            model_name='basket',
            name='deliverydate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_accounts.DeliveryDate'),
        ),
    ]
