# Generated by Django 2.2.12 on 2020-06-15 12:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0061_auto_20200615_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydate',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(50)]),
        ),
    ]
