# Generated by Django 2.2.12 on 2020-06-17 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0062_auto_20200615_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
