# Generated by Django 2.2.12 on 2020-06-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0063_basket_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='position',
            field=models.CharField(blank=True, choices=[('1', 'اماده سازی سفارش'), ('2', 'خروج  از مرکز پردازش'), ('3', 'دریافت در مرکز توزیع'), ('4', 'تحویل به مامور ارسال'), ('5', 'تحویل مرسوله به مشتری')], max_length=1, null=True),
        ),
    ]
