# Generated by Django 2.2.12 on 2020-06-20 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0064_basket_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='delivery_date',
        ),
    ]
