# Generated by Django 2.2.12 on 2020-06-24 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0065_remove_basket_delivery_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturningDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_range', models.CharField(blank=True, choices=[('A', '9-14'), ('B', '14-8')], max_length=1, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='basketitem',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='Returning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0, null=True)),
                ('reason', models.CharField(choices=[('1', 'سفارش به صورت کامل ارسال نشده'), ('2', 'سایز کالا مناسب نیست'), ('3', 'کالای غیر اصل دریافت کرده ام'), ('4', 'کالای دیگری ارسال شده است'), ('5', 'از خرید خود منصرف شدم'), ('6', 'رنگ کالای ارسال شده مغایرت دارد'), ('7', 'کالا با اطلاعات درج شده در سایت مغایرت دارد'), ('8', 'کالا ایراد ظاهری یا شکستگی دارد'), ('9', 'کارت گارانتی ارسال نشده')], max_length=1, null=True)),
                ('descriptions', models.TextField(max_length=3000, null=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('canceled', 'canceled'), ('accepted', 'accepted'), ('received', 'received')], max_length=10, null=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_accounts.Address')),
                ('basket_item', models.ManyToManyField(to='app_accounts.BasketItem')),
                ('returning_date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_accounts.ReturningDate')),
            ],
        ),
    ]
