# Generated by Django 2.2.12 on 2020-06-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0067_auto_20200624_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='returningdate',
            name='returning_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
