# Generated by Django 2.2.12 on 2020-06-25 11:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0070_returningbasket_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='returningbasket',
            name='registration_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='returningdate',
            name='capacity',
            field=models.PositiveIntegerField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(50)]),
        ),
    ]
