# Generated by Django 2.2.12 on 2020-06-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0071_auto_20200625_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='delivered',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='basket',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('favorites', 'favorites'), ('pardakht', 'pardakht'), ('pardakht-shod', 'pardakht-shod'), ('canceled', 'canceled')], max_length=30, null=True),
        ),
    ]
