# Generated by Django 2.2.12 on 2020-06-28 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0072_auto_20200627_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='returningbasket',
            name='basket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_accounts.Basket'),
        ),
    ]
