# Generated by Django 2.2.12 on 2020-06-28 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0073_returningbasket_basket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='shipping_cost',
        ),
    ]
