# Generated by Django 2.2.12 on 2020-07-03 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0074_remove_basket_shipping_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodbadpoint',
            name='item',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='goodbadpoint',
            name='point',
            field=models.CharField(choices=[('good', 'goodpoint'), ('bad', 'badpoint')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='returningbasket',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_accounts.Address'),
        ),
        migrations.AlterField(
            model_name='returningbasket',
            name='returning_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_accounts.ReturningDate'),
        ),
    ]
