# Generated by Django 2.2.12 on 2020-07-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0075_auto_20200703_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodbadpoint',
            name='point',
            field=models.CharField(choices=[('good', 'goodpoint'), ('bad', 'badpoint')], default='good', max_length=10, null=True),
        ),
    ]
