# Generated by Django 2.2.12 on 2020-07-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0076_auto_20200703_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='write_date',
            field=models.DateField(null=True),
        ),
    ]
