# Generated by Django 2.2.12 on 2020-07-10 08:11

import app_accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0077_auto_20200703_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='most_liked',
        ),
        migrations.AlterField(
            model_name='address',
            name='mailing_code',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10), app_accounts.models.validate_mailing_code]),
        ),
        migrations.AlterField(
            model_name='address',
            name='reciver_cellphone',
            field=models.CharField(max_length=11, null=True, validators=[django.core.validators.MinLengthValidator(11), app_accounts.models.validate_cellphone]),
        ),
        migrations.AlterField(
            model_name='basket',
            name='total_price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='count_dislike',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='count_like',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='dislike',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='like',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
