# Generated by Django 2.2.12 on 2020-07-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0079_auto_20200710_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='offer',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
