# Generated by Django 2.2.12 on 2020-07-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0080_comment_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='offer',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No'), ('S', 'so-so')], max_length=1, null=True),
        ),
    ]
