# Generated by Django 2.2.12 on 2020-07-12 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0081_auto_20200711_0902'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('C', 'canceled'), ('R', 'returned')], max_length=1, null=True)),
                ('state', models.CharField(choices=[('1', 'variz shode'), ('2', 'variz nashode')], max_length=1, null=True)),
                ('amount', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('basket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_accounts.Basket')),
            ],
        ),
    ]
