# Generated by Django 2.2.12 on 2020-07-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0082_refundamount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refundamount',
            name='state',
        ),
        migrations.AddField(
            model_name='refundamount',
            name='paid',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
