# Generated by Django 2.2.12 on 2020-07-13 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0083_auto_20200712_0839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returningitem',
            old_name='refund_amount',
            new_name='purchase_amount',
        ),
    ]
