# Generated by Django 2.2.12 on 2020-07-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='color_hex',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='colors',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
