# Generated by Django 2.2.12 on 2020-04-17 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cellphone',
            name='image',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='image',
        ),
        migrations.RemoveField(
            model_name='tablet',
            name='image',
        ),
        migrations.RemoveField(
            model_name='television',
            name='image',
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(null=True, upload_to='app_product/images')),
                ('cellphone1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_product.Cellphone')),
            ],
        ),
    ]
