# Generated by Django 2.2.12 on 2020-04-17 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0003_auto_20200417_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='cellphone1',
            new_name='cellphone',
        ),
    ]
