# Generated by Django 2.2.12 on 2020-07-28 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0003_auto_20200728_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cellphone',
            name='status',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='status',
        ),
        migrations.RemoveField(
            model_name='tablet',
            name='status',
        ),
        migrations.RemoveField(
            model_name='television',
            name='status',
        ),
    ]
