# Generated by Django 2.2.12 on 2020-04-17 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0004_auto_20200417_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='height',
        ),
        migrations.RemoveField(
            model_name='album',
            name='width',
        ),
    ]
