# Generated by Django 2.2.12 on 2020-07-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0004_auto_20200728_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellphone',
            name='status',
            field=models.CharField(choices=[('A', 'در دسترس'), ('S', 'به زودی'), ('O', 'اتمام موجودی')], default='A', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='status',
            field=models.CharField(choices=[('A', 'در دسترس'), ('S', 'به زودی'), ('O', 'اتمام موجودی')], default='A', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tablet',
            name='status',
            field=models.CharField(choices=[('A', 'در دسترس'), ('S', 'به زودی'), ('O', 'اتمام موجودی')], default='A', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='television',
            name='status',
            field=models.CharField(choices=[('A', 'در دسترس'), ('S', 'به زودی'), ('O', 'اتمام موجودی')], default='A', max_length=1, null=True),
        ),
    ]
