# Generated by Django 2.2.12 on 2020-04-22 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0005_auto_20200417_1358'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Album',
        ),
    ]
