# Generated by Django 2.2.12 on 2020-04-22 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0001_initial'),
        ('app_product', '0006_delete_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellphone',
            name='basket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_accounts.Basket'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='basket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_accounts.Basket'),
        ),
        migrations.AddField(
            model_name='tablet',
            name='basket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_accounts.Basket'),
        ),
        migrations.AddField(
            model_name='television',
            name='basket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_accounts.Basket'),
        ),
    ]
