# Generated by Django 2.2.12 on 2020-04-27 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0007_auto_20200422_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cellphone',
            name='basket',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='basket',
        ),
        migrations.RemoveField(
            model_name='tablet',
            name='basket',
        ),
        migrations.RemoveField(
            model_name='television',
            name='basket',
        ),
        migrations.AddField(
            model_name='cellphone',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='laptop',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tablet',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='television',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
