# Generated by Django 2.2.12 on 2020-04-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0008_auto_20200427_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellphone',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='television',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
