# Generated by Django 2.2.12 on 2020-05-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0009_auto_20200429_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellphone',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tablet',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='television',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
