# Generated by Django 2.2.12 on 2020-05-06 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0010_auto_20200502_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='app_product/images')),
                ('cellphone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_product.Cellphone')),
            ],
        ),
    ]
