# Generated by Django 2.2.12 on 2020-05-12 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0011_album'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Album',
        ),
    ]
