# Generated by Django 2.2.12 on 2020-05-26 12:49

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0012_delete_album'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cellphone',
            managers=[
                ('sm', django.db.models.manager.Manager()),
            ],
        ),
    ]
