# Generated by Django 2.2.12 on 2020-05-26 18:10

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0013_auto_20200526_1249'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='television',
            managers=[
                ('sm', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='television',
            name='brand',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
