# Generated by Django 2.2.12 on 2020-07-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0016_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='image',
        ),
        migrations.AddField(
            model_name='album',
            name='img',
            field=models.ImageField(blank=True, default='Images/None/No-img.jpg', null=True, upload_to='app_product/images'),
        ),
    ]
