# Generated by Django 2.2.12 on 2020-07-08 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0017_auto_20200708_0703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='img',
            new_name='image',
        ),
    ]
