# Generated by Django 2.2.12 on 2020-07-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0018_auto_20200708_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='video',
            field=models.FileField(blank=True, default='videos/None/No-img.pdf', null=True, upload_to='app_product/videos'),
        ),
    ]
